:AllowTypeErrors

def succ: int -> int
//│ succ: int -> int


x1 = false
x2 = x1
x3 = x2
//│ x1: false
//│ x2: false
//│ x3: false

:ex
succ x3
//│ ╔══[ERROR] Type mismatch in application:
//│ ║  l.15: 	succ x3
//│ ║        	^^^^^^^
//│ ╟── reference of type `false` is not an instance of type `int`
//│ ║  l.7: 	x1 = false
//│ ║       	     ^^^^^
//│ ╟── but it flows into reference with expected type `int`
//│ ║  l.15: 	succ x3
//│ ║        	     ^^
//│ ╟── Note: constraint arises from type reference:
//│ ║  l.3: 	def succ: int -> int
//│ ║       	          ^^^
//│ ╟── ========= Additional explanations below =========
//│ ╟── [info] flowing from type `false`
//│ ╟── [info] flowing from reference of type `false`
//│ ║  l.7: 	x1 = false
//│ ║       	     ^^^^^
//│ ╟── [info] flowing from reference of type `false`
//│ ║  l.7: 	x1 = false
//│ ║       	     ^^^^^
//│ ╟── [info] flowing from reference of type `false`
//│ ║  l.8: 	x2 = x1
//│ ║       	     ^^
//│ ╟── [info] flowing from reference of type `false`
//│ ║  l.8: 	x2 = x1
//│ ║       	     ^^
//│ ╟── [info] flowing from reference of type `false`
//│ ║  l.9: 	x3 = x2
//│ ║       	     ^^
//│ ╟── [info] flowing from reference of type `false`
//│ ║  l.9: 	x3 = x2
//│ ║       	     ^^
//│ ╟── [info] flowing from reference of type `false`
//│ ║  l.15: 	succ x3
//│ ║        	     ^^
//│ ╟── [info] flowing into type `int`
//│ ║  l.3: 	def succ: int -> int
//│ ║       	          ^^^
//│ ╟── [info] flowing into type `int`
//│ ║  l.3: 	def succ: int -> int
//│ ╙──     	          ^^^
//│ res: error


f1 y1 = succ y1
f2 y2 = f1 y2
f3 y3 = f2 y3
//│ f1: int -> int
//│ f2: int -> (forall 'a. int | 'a)
//│ f3: int -> (forall 'a, 'b. int | 'a | 'b)

:ex
f3 true
//│ ╔══[ERROR] Type mismatch in application:
//│ ║  l.68: 	f3 true
//│ ║        	^^^^^^^
//│ ╟── reference of type `true` is not an instance of type `int`
//│ ║  l.68: 	f3 true
//│ ║        	   ^^^^
//│ ╟── Note: constraint arises from type reference:
//│ ║  l.3: 	def succ: int -> int
//│ ║       	          ^^^
//│ ╟── from reference:
//│ ║  l.62: 	f3 y3 = f2 y3
//│ ║        	           ^^
//│ ╟── ========= Additional explanations below =========
//│ ╟── [info] flowing from type `true`
//│ ╟── [info] flowing from reference of type `true`
//│ ║  l.68: 	f3 true
//│ ║        	   ^^^^
//│ ╟── [info] flowing into variable of type `?a`
//│ ╟── [info] flowing into variable of type `?b`
//│ ╟── [info] flowing into reference of type `?c`
//│ ║  l.62: 	f3 y3 = f2 y3
//│ ║        	           ^^
//│ ╟── [info] flowing into variable of type `?d`
//│ ╟── [info] flowing into variable of type `?e`
//│ ╟── [info] flowing into variable of type `?f`
//│ ╟── [info] flowing into reference of type `?g`
//│ ║  l.61: 	f2 y2 = f1 y2
//│ ║        	           ^^
//│ ╟── [info] flowing into variable of type `?h`
//│ ╟── [info] flowing into variable of type `?i`
//│ ╟── [info] flowing into variable of type `int`
//│ ╟── [info] flowing into reference of type `int`
//│ ║  l.60: 	f1 y1 = succ y1
//│ ║        	             ^^
//│ ╟── [info] flowing into type `int`
//│ ║  l.3: 	def succ: int -> int
//│ ║       	          ^^^
//│ ╟── [info] flowing into type `int`
//│ ║  l.3: 	def succ: int -> int
//│ ║       	          ^^^
//│ ╟── [info] flowing into type `int`
//│ ║  l.3: 	def succ: int -> int
//│ ╙──     	          ^^^
//│ res: error


:ex
f3 x3
//│ ╔══[ERROR] Type mismatch in application:
//│ ║  l.116: 	f3 x3
//│ ║         	^^^^^
//│ ╟── reference of type `false` is not an instance of type `int`
//│ ║  l.7: 	x1 = false
//│ ║       	     ^^^^^
//│ ╟── but it flows into reference with expected type `int`
//│ ║  l.116: 	f3 x3
//│ ║         	   ^^
//│ ╟── Note: constraint arises from type reference:
//│ ║  l.3: 	def succ: int -> int
//│ ║       	          ^^^
//│ ╟── from reference:
//│ ║  l.62: 	f3 y3 = f2 y3
//│ ║        	           ^^
//│ ╟── ========= Additional explanations below =========
//│ ╟── [info] flowing from type `false`
//│ ╟── [info] flowing from reference of type `false`
//│ ║  l.7: 	x1 = false
//│ ║       	     ^^^^^
//│ ╟── [info] flowing from reference of type `false`
//│ ║  l.7: 	x1 = false
//│ ║       	     ^^^^^
//│ ╟── [info] flowing from reference of type `false`
//│ ║  l.8: 	x2 = x1
//│ ║       	     ^^
//│ ╟── [info] flowing from reference of type `false`
//│ ║  l.8: 	x2 = x1
//│ ║       	     ^^
//│ ╟── [info] flowing from reference of type `false`
//│ ║  l.9: 	x3 = x2
//│ ║       	     ^^
//│ ╟── [info] flowing from reference of type `false`
//│ ║  l.9: 	x3 = x2
//│ ║       	     ^^
//│ ╟── [info] flowing from reference of type `false`
//│ ║  l.116: 	f3 x3
//│ ║         	   ^^
//│ ╟── [info] flowing into variable of type `?a`
//│ ╟── [info] flowing into variable of type `?b`
//│ ╟── [info] flowing into reference of type `?c`
//│ ║  l.62: 	f3 y3 = f2 y3
//│ ║        	           ^^
//│ ╟── [info] flowing into variable of type `?d`
//│ ╟── [info] flowing into variable of type `?e`
//│ ╟── [info] flowing into variable of type `?f`
//│ ╟── [info] flowing into reference of type `?g`
//│ ║  l.61: 	f2 y2 = f1 y2
//│ ║        	           ^^
//│ ╟── [info] flowing into variable of type `?h`
//│ ╟── [info] flowing into variable of type `?i`
//│ ╟── [info] flowing into variable of type `int`
//│ ╟── [info] flowing into reference of type `int`
//│ ║  l.60: 	f1 y1 = succ y1
//│ ║        	             ^^
//│ ╟── [info] flowing into type `int`
//│ ║  l.3: 	def succ: int -> int
//│ ║       	          ^^^
//│ ╟── [info] flowing into type `int`
//│ ║  l.3: 	def succ: int -> int
//│ ║       	          ^^^
//│ ╟── [info] flowing into type `int`
//│ ║  l.3: 	def succ: int -> int
//│ ╙──     	          ^^^
//│ res: error


h1 f x = f x
h2 f x = h1 f x
h3 f x = h2 f x
//│ h1: ('a -> 'b) -> 'a -> 'b
//│ h2: ('a -> 'b) -> 'a -> 'b
//│ h3: ('a -> 'b) -> 'a -> 'b

:ex
h3 f3 x3
//│ ╔══[ERROR] Type mismatch in application:
//│ ║  l.192: 	h3 f3 x3
//│ ║         	^^^^^^^^
//│ ╟── reference of type `false` is not an instance of type `int`
//│ ║  l.7: 	x1 = false
//│ ║       	     ^^^^^
//│ ╟── but it flows into reference with expected type `int`
//│ ║  l.192: 	h3 f3 x3
//│ ║         	      ^^
//│ ╟── Note: constraint arises from type reference:
//│ ║  l.3: 	def succ: int -> int
//│ ║       	          ^^^
//│ ╟── from reference:
//│ ║  l.186: 	h3 f x = h2 f x
//│ ║         	              ^
//│ ╟── ========= Additional explanations below =========
//│ ╟── [info] flowing from type `false`
//│ ╟── [info] flowing from reference of type `false`
//│ ║  l.7: 	x1 = false
//│ ║       	     ^^^^^
//│ ╟── [info] flowing from reference of type `false`
//│ ║  l.7: 	x1 = false
//│ ║       	     ^^^^^
//│ ╟── [info] flowing from reference of type `false`
//│ ║  l.8: 	x2 = x1
//│ ║       	     ^^
//│ ╟── [info] flowing from reference of type `false`
//│ ║  l.8: 	x2 = x1
//│ ║       	     ^^
//│ ╟── [info] flowing from reference of type `false`
//│ ║  l.9: 	x3 = x2
//│ ║       	     ^^
//│ ╟── [info] flowing from reference of type `false`
//│ ║  l.9: 	x3 = x2
//│ ║       	     ^^
//│ ╟── [info] flowing from reference of type `false`
//│ ║  l.192: 	h3 f3 x3
//│ ║         	      ^^
//│ ╟── [info] flowing into variable of type `?a`
//│ ╟── [info] flowing into variable of type `?b`
//│ ╟── [info] flowing into reference of type `?c`
//│ ║  l.186: 	h3 f x = h2 f x
//│ ║         	              ^
//│ ╟── [info] flowing into variable of type `?d`
//│ ╟── [info] flowing into variable of type `?e`
//│ ╟── [info] flowing into variable of type `?f`
//│ ╟── [info] flowing into reference of type `?g`
//│ ║  l.185: 	h2 f x = h1 f x
//│ ║         	              ^
//│ ╟── [info] flowing into variable of type `?h`
//│ ╟── [info] flowing into variable of type `?i`
//│ ╟── [info] flowing into variable of type `?j`
//│ ╟── [info] flowing into reference of type `?k`
//│ ║  l.184: 	h1 f x = f x
//│ ║         	           ^
//│ ╟── [info] flowing into variable of type `?l`
//│ ╟── [info] flowing into variable of type `?m`
//│ ╟── [info] flowing into variable of type `?n`
//│ ╟── [info] flowing into reference of type `?o`
//│ ║  l.62: 	f3 y3 = f2 y3
//│ ║        	           ^^
//│ ╟── [info] flowing into variable of type `?p`
//│ ╟── [info] flowing into variable of type `?q`
//│ ╟── [info] flowing into variable of type `?r`
//│ ╟── [info] flowing into reference of type `?s`
//│ ║  l.61: 	f2 y2 = f1 y2
//│ ║        	           ^^
//│ ╟── [info] flowing into variable of type `?t`
//│ ╟── [info] flowing into variable of type `?u`
//│ ╟── [info] flowing into variable of type `int`
//│ ╟── [info] flowing into reference of type `int`
//│ ║  l.60: 	f1 y1 = succ y1
//│ ║        	             ^^
//│ ╟── [info] flowing into type `int`
//│ ║  l.3: 	def succ: int -> int
//│ ║       	          ^^^
//│ ╟── [info] flowing into type `int`
//│ ║  l.3: 	def succ: int -> int
//│ ║       	          ^^^
//│ ╟── [info] flowing into type `int`
//│ ║  l.3: 	def succ: int -> int
//│ ╙──     	          ^^^
//│ res: error


:ex
(fun x -> succ x) false
//│ ╔══[ERROR] Type mismatch in application:
//│ ║  l.279: 	(fun x -> succ x) false
//│ ║         	^^^^^^^^^^^^^^^^^^^^^^^
//│ ╟── reference of type `false` is not an instance of type `int`
//│ ║  l.279: 	(fun x -> succ x) false
//│ ║         	                  ^^^^^
//│ ╟── Note: constraint arises from type reference:
//│ ║  l.3: 	def succ: int -> int
//│ ║       	          ^^^
//│ ╟── from reference:
//│ ║  l.279: 	(fun x -> succ x) false
//│ ║         	               ^
//│ ╟── ========= Additional explanations below =========
//│ ╟── [info] flowing from type `false`
//│ ╟── [info] flowing from reference of type `false`
//│ ║  l.279: 	(fun x -> succ x) false
//│ ║         	                  ^^^^^
//│ ╟── [info] flowing into variable of type `?a`
//│ ╟── [info] flowing into variable of type `int`
//│ ╟── [info] flowing into reference of type `int`
//│ ║  l.279: 	(fun x -> succ x) false
//│ ║         	               ^
//│ ╟── [info] flowing into type `int`
//│ ║  l.3: 	def succ: int -> int
//│ ║       	          ^^^
//│ ╟── [info] flowing into type `int`
//│ ║  l.3: 	def succ: int -> int
//│ ║       	          ^^^
//│ ╟── [info] flowing into type `int`
//│ ║  l.3: 	def succ: int -> int
//│ ╙──     	          ^^^
//│ res: error

// :d
:ex
rec def x = add x
//│ ╔══[ERROR] Type mismatch in binding of application:
//│ ║  l.315: 	rec def x = add x
//│ ║         	            ^^^^^
//│ ╟── application of type `int -> int` is not an instance of type `int`
//│ ╟── Note: constraint arises from reference:
//│ ║  l.315: 	rec def x = add x
//│ ║         	                ^
//│ ╟── ========= Additional explanations below =========
//│ ╟── [info] flowing from expression of type `int -> int`
//│ ╟── [info] flowing from application of type `int -> int`
//│ ║  l.315: 	rec def x = add x
//│ ║         	            ^^^^^
//│ ╟── [info] flowing from application of type `?a`
//│ ║  l.315: 	rec def x = add x
//│ ║         	            ^^^^^
//│ ╟── [info] flowing into expression of type `?x`
//│ ╟── [info] flowing into reference of type `int`
//│ ║  l.315: 	rec def x = add x
//│ ║         	                ^
//│ ╟── [info] flowing into type `int`
//│ ╙── [info] flowing into type `int`
//│ x: int -> int


def foo: int | string
//│ foo: int | string

:ex
succ foo
//│ ╔══[ERROR] Type mismatch in application:
//│ ║  l.344: 	succ foo
//│ ║         	^^^^^^^^
//│ ╟── type `string` is not an instance of `int`
//│ ║  l.340: 	def foo: int | string
//│ ║         	               ^^^^^^
//│ ╟── but it flows into reference with expected type `int`
//│ ║  l.344: 	succ foo
//│ ║         	     ^^^
//│ ╟── Note: constraint arises from type reference:
//│ ║  l.3: 	def succ: int -> int
//│ ║       	          ^^^
//│ ╟── ========= Additional explanations below =========
//│ ╟── [info] flowing from type `string`
//│ ║  l.340: 	def foo: int | string
//│ ║         	               ^^^^^^
//│ ╟── [info] flowing from type `int | string`
//│ ║  l.340: 	def foo: int | string
//│ ║         	         ^^^^^^^^^^^^
//│ ╟── [info] flowing from reference of type `int | string`
//│ ║  l.344: 	succ foo
//│ ║         	     ^^^
//│ ╟── [info] flowing into type `int`
//│ ║  l.3: 	def succ: int -> int
//│ ╙──     	          ^^^
//│ res: error



class A
class B
//│ Defined class A
//│ Defined class B

def ty00: ('a & A | 'b & B) -> ('a, 'b)
//│ ty00: (A & 'a | B & 'b) -> ('a, 'b,)

def ty11: ('a & A | 'a & B) -> ('a, 'a)
//│ ty11: ('a & (A | B)) -> ('a, 'a,)

ty11 = ty00
//│ (A & 'a | B & 'b) -> ('a, 'b,)
//│   <:  ty11:
//│ ('a & (A | B)) -> ('a, 'a,)

// :d
:ex
ty00 = ty11
//│ ('a & (A | B)) -> ('a, 'a,)
//│   <:  ty00:
//│ (A & 'a | B & 'b) -> ('a, 'b,)
//│ ╔══[ERROR] Type mismatch in def definition:
//│ ║  l.392: 	ty00 = ty11
//│ ║         	^^^^^^^^^^^
//│ ╟── type `B & ‘b_285` is not an instance of type `'a_284`
//│ ║  l.379: 	def ty00: ('a & A | 'b & B) -> ('a, 'b)
//│ ║         	                    ^^^^^^
//│ ╟── Note: constraint arises from type variable:
//│ ║  l.379: 	def ty00: ('a & A | 'b & B) -> ('a, 'b)
//│ ║         	                                ^^
//│ ╟── ========= Additional explanations below =========
//│ ╟── [info] flowing from expression of type `B & ‘b_285`
//│ ╟── [info] flowing from type `B & ‘b_285`
//│ ║  l.379: 	def ty00: ('a & A | 'b & B) -> ('a, 'b)
//│ ║         	                    ^^^^^^
//│ ╟── [info] flowing from type `B & ‘b_285`
//│ ║  l.379: 	def ty00: ('a & A | 'b & B) -> ('a, 'b)
//│ ║         	          ^^^^^^^^^^^^^^^^^
//│ ╟── [info] flowing from type `B & ‘b_285`
//│ ║  l.382: 	def ty11: ('a & A | 'a & B) -> ('a, 'a)
//│ ║         	          ^^^^^^^^^^^^^^^^^
//│ ╟── [info] flowing from expression of type `?a`
//│ ╟── [info] flowing from type `?a0`
//│ ║  l.382: 	def ty11: ('a & A | 'a & B) -> ('a, 'a)
//│ ║         	                                ^^
//│ ╟── [info] flowing into type `‘a_284`
//│ ║  l.379: 	def ty00: ('a & A | 'b & B) -> ('a, 'b)
//│ ║         	                                ^^
//│ ╙── [info] flowing into expression of type `‘a_284`

